import type { ApiKeysConfig, ChatConfig, ProfileFlattened } from './settingsTypes';

export const DEFAULT_API_KEYS: ApiKeysConfig = {
  gemini_api_key_paid: '',
  gemini_api_key_free: '',
  openrouter_api_key: '',
  openrouter_model_name: 'deepseek/deepseek-r1:free',
  model_capabilities_overrides: '',
  google_model_flash: 'gemini-2.5-flash',
  google_model_lite: 'gemini-3.1-flash-lite-preview',
  google_model_vision: 'gemini-2.5-flash',
  google_model_search: 'gemini-3.1-flash-lite-preview',
  google_model_memory: 'gemini-3.1-flash-lite-preview',
  ollama_base_url: 'http://localhost:11434',
  ollama_chat_model: 'gpt-oss:20b',
  ollama_vision_patterns: 'vision,llava,llama3.2-vision,llama4,gemma4',
  gemma4_enabled: true,
  gemma4_model_31b: 'gemma-4-31b-it',
  gemma4_model_26b: 'gemma-4-26b-a4b',
  google_api_key_search: '',
  google_api_key_search_b: '',
  cse_api_key: '',
  cse_cx: '',
  google_api_key_vision_a: '',
  google_api_key_vision_b: '',
  google_api_key_manager: '',
  spotipy_client_id: '',
  spotipy_client_secret: '',
  spotipy_redirect_uri: 'http://localhost:8888/callback',
  google_ai_studio_api_key: '',
  deepinfra_api_key: '',
  gh_token: '',
  gist_id: '',
};

export const DEFAULT_CHAT: ChatConfig = {
  default_engine: 'LITE',
  streaming_enabled: true,
  max_history_messages: 50,
  auto_save_tags: true,
  show_timestamps: true,
  compaction_threshold: 30,
  compaction_recent_window: 15,
  reasoning_level: 'off',
  internet_search_enabled: false,
};

export const DEFAULT_PROFILE: ProfileFlattened = {
  name: 'Sitr3n',
  archetype: 'Humanista Melancolico',
  learning_style: 'Associacao com Lore/Narrativa',
  bio: '',
  personality: [],
  occupation: '',
  interests: [
    'Anime (Violet Evergarden, Frieren, Diarios de uma Apotecaria)',
    'Lore de Jogos (HSR, Genshin, LoL, Valorant, WuWa)',
    'Audiofilia',
    'Antropologia',
    'Sociologia',
    'Cosplay',
    'Hardware avancado',
    'Software',
    'Historia',
    'Filosofia',
    'Aviacao',
    'Fotografia',
    'Filmografia',
  ],
  tech_stack: ['Unity', 'Python', 'Internet'],
  music: ['MPB', 'Bossa Nova', 'Eletronica', 'J-pop', 'K-pop', 'Orquestra', 'Lo-fi'],
  dislikes: ['Respostas secas', 'Falta de profundidade'],
  foods: [],
  languages: { Japanese: 'N5' },
};
